# This is CodeCademy Project "Hurricane Analysis" and my own solustions.

### Provided data:

In [1]:
# names of hurricanes
names = ['Cuba I', 'San Felipe II Okeechobee', 'Bahamas', 'Cuba II', 'CubaBrownsville', 'Tampico', 
         'Labor Day', 'New England', 'Carol', 'Janet', 'Carla', 'Hattie', 'Beulah', 'Camille', 'Edith', 
         'Anita', 'David', 'Allen', 'Gilbert', 'Hugo', 'Andrew', 'Mitch', 'Isabel', 'Ivan', 'Emily', 
         'Katrina', 'Rita', 'Wilma', 'Dean', 'Felix', 'Matthew', 'Irma', 'Maria', 'Michael']

# months of hurricanes
months = ['October', 'September', 'September', 'November', 'August', 'September', 'September', 'September', 
          'September', 'September', 'September', 'October', 'September', 'August', 'September', 'September', 
          'August', 'August', 'September', 'September', 'August', 'October', 'September', 'September', 'July', 
          'August', 'September', 'October', 'August', 'September', 'October', 'September', 'September', 'October']

# years of hurricanes
years = [1924, 1928, 1932, 1932, 1933, 1933, 1935, 1938, 1953, 1955, 1961, 1961, 1967, 1969, 1971, 1977, 1979, 1980, 
         1988, 1989, 1992, 1998, 2003, 2004, 2005, 2005, 2005, 2005, 2007, 2007, 2016, 2017, 2017, 2018]

# maximum sustained winds (mph) of hurricanes
max_sustained_winds = [165, 160, 160, 175, 160, 160, 185, 160, 160, 175, 175, 160, 160, 175, 160, 175, 175, 190, 185, 160, 
                       175, 180, 165, 165, 160, 175, 180, 185, 175, 175, 165, 180, 175, 160]

# areas affected by each hurricane
areas_affected = [['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 
                  ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], 
                  ['The Bahamas', 'Northeastern United States'], 
                  ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 
                  ['The Bahamas', 'Cuba', 'Florida', 'Texas', 'Tamaulipas'], 
                  ['Jamaica', 'Yucatn Peninsula'], 
                  ['The Bahamas', 'Florida', 'Georgia', 'The Carolinas', 'Virginia'], 
                  ['Southeastern United States', 'Northeastern United States', 'Southwestern Quebec'], 
                  ['Bermuda', 'New England', 'Atlantic Canada'], 
                  ['Lesser Antilles', 'Central America'], 
                  ['Texas', 'Louisiana', 'Midwestern United States'], 
                  ['Central America'], 
                  ['The Caribbean', 'Mexico', 'Texas'], 
                  ['Cuba', 'United States Gulf Coast'], 
                  ['The Caribbean', 'Central America', 'Mexico', 'United States Gulf Coast'], 
                  ['Mexico'], ['The Caribbean', 'United States East coast'], 
                  ['The Caribbean', 'Yucatn Peninsula', 'Mexico', 'South Texas'], 
                  ['Jamaica', 'Venezuela', 'Central America', 'Hispaniola', 'Mexico'], 
                  ['The Caribbean', 'United States East Coast'], 
                  ['The Bahamas', 'Florida', 'United States Gulf Coast'], 
                  ['Central America', 'Yucatn Peninsula', 'South Florida'], 
                  ['Greater Antilles', 'Bahamas', 'Eastern United States', 'Ontario'], 
                  ['The Caribbean', 'Venezuela', 'United States Gulf Coast'], 
                  ['Windward Islands', 'Jamaica', 'Mexico', 'Texas'], 
                  ['Bahamas', 'United States Gulf Coast'], 
                  ['Cuba', 'United States Gulf Coast'], 
                  ['Greater Antilles', 'Central America', 'Florida'], 
                  ['The Caribbean', 'Central America'], 
                  ['Nicaragua', 'Honduras'], 
                  ['Antilles', 'Venezuela', 'Colombia', 'United States East Coast', 'Atlantic Canada'], 
                  ['Cape Verde', 'The Caribbean', 'British Virgin Islands', 'U.S. Virgin Islands', 'Cuba', 'Florida'], 
                  ['Lesser Antilles', 'Virgin Islands', 'Puerto Rico', 'Dominican Republic', 'Turks and Caicos Islands'], 
                  ['Central America', 'United States Gulf Coast (especially Florida Panhandle)']]

# damages (USD($)) of hurricanes
damages = ['Damages not recorded', '100M', 'Damages not recorded', '40M', '27.9M', '5M', 'Damages not recorded', '306M', 
           '2M', '65.8M', '326M', '60.3M', '208M', '1.42B', '25.4M', 'Damages not recorded', '1.54B', '1.24B', '7.1B', 
           '10B', '26.5B', '6.2B', '5.37B', '23.3B', '1.01B', '125B', '12B', '29.4B', '1.76B', '720M', '15.1B', '64.8B', 
           '91.6B', '25.1B']

# deaths for each hurricane
deaths = [90,4000,16,3103,179,184,408,682,5,1023,43,319,688,259,37,11,2068,269,318,107,65,19325,51,124,17,1836,125,87,
          45,133,603,138,3057,74]

# Task 1

Hurricanes, also known as cyclones or typhoons, are one of the most powerful forces of nature on Earth. Due to climate change caused by human activity, the number and intensity of hurricanes has risen, calling for better preparation by the many communities that are devastated by them. As a concerned environmentalist, you want to look at data about the most powerful hurricanes that have occurred.

Begin by looking at the damages list. The list contains strings representing the total cost in USD($) caused by 34 category 5 hurricanes (wind speeds ≥ 157 mph (252 km/h )) in the Atlantic region. For some of the hurricanes, damage data was not recorded ("Damages not recorded"), while the rest are written in the format "Prefix-B/M", where B stands for billions (1000000000) and M stands for millions (1000000).

Write a function that returns a new list of updated damages where the recorded data is converted to float values and the missing data is retained as "Damages not recorded".

Test your function with the data stored in damages.

In [2]:
def update_damages(damages_list):
    updated_damages_list = []
    for damage in damages_list:
        if damage[-1] == 'B':
            updated_damages_list.append(float(damage[:-1])*1000000000)
        elif damage[-1] == 'M':
            updated_damages_list.append(float(damage[:-1])*1000000)
        elif damage == "Damages not recorded":
            updated_damages_list.append(0)
        else:
            updated_damages_list.append(None)
    return updated_damages_list

In [3]:
updated_damages = update_damages(damages)
print(updated_damages)

[0, 100000000.0, 0, 40000000.0, 27900000.0, 5000000.0, 0, 306000000.0, 2000000.0, 65800000.0, 326000000.0, 60300000.0, 208000000.0, 1420000000.0, 25400000.0, 0, 1540000000.0, 1240000000.0, 7100000000.0, 10000000000.0, 26500000000.0, 6200000000.0, 5370000000.0, 23300000000.0, 1010000000.0, 125000000000.0, 12000000000.0, 29400000000.0, 1760000000.0, 720000000.0, 15100000000.0, 64800000000.0, 91600000000.0, 25100000000.0]


# Task 2

Additional data collected on the 34 strongest Atlantic hurricanes are provided in a series of lists. The data includes:
- names: names of the hurricanes
- months: months in which the hurricanes occurred
- years: years in which the hurricanes occurred
- max_sustained_winds: maximum sustained winds (miles per hour) of the hurricanes
- areas_affected: list of different areas affected by each of the hurricanes
- deaths: total number of deaths caused by each of the hurricanes

The data is organized such that the data at each index, from 0 to 33, corresponds to the same hurricane.

For example, names[0] yields the “Cuba I” hurricane, which ouccred in months[0] (October) years[0] (1924).

Write a function that constructs a dictionary made out of the lists, where the keys of the dictionary are the names of the hurricanes, and the values are dictionaries themselves containing a key for each piece of data (Name, Month, Year,Max Sustained Wind, Areas Affected, Damage, Death) about the hurricane.

Thus the key "Cuba I" would have the value: {'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Deaths': 90}.

Test your function on the lists of data provided.

In [4]:
def construct_hurricane_dictionary(names, months, years, max_sustained_winds, areas_affected, damages, deaths):
    hurricane_keys = ['Name', 'Month', 'Year', 'Max Sustained Wind', 'Areas Affected', 'Damage', 'Deaths']
    hurricane_values = [names, months, years, max_sustained_winds, areas_affected, damages, deaths]
    hurricane_dictionary = {}
    for i in range(len(names)):
        hurricane_dictionary[names[i]] = {key:value[i] for (key,value) in zip (hurricane_keys,hurricane_values)}
    return hurricane_dictionary

In [5]:
hurricane_name_dictionary = construct_hurricane_dictionary(names, months, years, max_sustained_winds, areas_affected, updated_damages, deaths)
for (key,value) in hurricane_name_dictionary.items():
    print("Hurricane '{key}': {value}".format(key=key,value=value))
    print()

Hurricane 'Cuba I': {'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 0, 'Deaths': 90}

Hurricane 'San Felipe II Okeechobee': {'Name': 'San Felipe II Okeechobee', 'Month': 'September', 'Year': 1928, 'Max Sustained Wind': 160, 'Areas Affected': ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], 'Damage': 100000000.0, 'Deaths': 4000}

Hurricane 'Bahamas': {'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 0, 'Deaths': 16}

Hurricane 'Cuba II': {'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}

Hurricane 'CubaBrownsville': {'Name': 'CubaBrownsville', 'Month': 'Au

# Task 3

In addition to organizing the hurricanes in a dictionary with names as the key, you want to be able to organize the hurricanes by year.

Write a function that converts the current dictionary of hurricanes to a new dictionary, where the keys are years and the values are lists containing a dictionary for each hurricane that occurred in that year.

For example, the key 1932 would yield the value: [{'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 'Damages not recorded', 'Deaths': 16}, {'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}].

Test your function on your hurricane dictionary.

In [6]:
def hurricane_by_year_dictionary(hurricane_by_name_dictionary):
    hurricane_by_year_dictionary = {}
    for (key,value) in hurricane_by_name_dictionary.items():
        if not value["Year"] in hurricane_by_year_dictionary:
            hurricane_by_year_dictionary[value["Year"]] = [value]
        else:
            hurricane_by_year_dictionary[value["Year"]].append(value)
    return hurricane_by_year_dictionary
            
hurricane_year_dictionary = hurricane_by_year_dictionary(hurricane_name_dictionary)
for (key,value) in hurricane_year_dictionary.items():
    print("{key}: {value}".format(key=key,value=value))
    print()

1924: [{'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 0, 'Deaths': 90}]

1928: [{'Name': 'San Felipe II Okeechobee', 'Month': 'September', 'Year': 1928, 'Max Sustained Wind': 160, 'Areas Affected': ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], 'Damage': 100000000.0, 'Deaths': 4000}]

1932: [{'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 0, 'Deaths': 16}, {'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}]

1933: [{'Name': 'CubaBrownsville', 'Month': 'August', 'Year': 1933, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Cuba', 'Florida

# Task 4
You believe that knowing how often each of the areas of the Atlantic are affected by these strong hurricanes is important for making preparations for future hurricanes.

Write a function that counts how often each area is listed as an affected area of a hurricane. Store and return the results in a dictionary where the keys are the affected areas and the values are counts of how many times the areas were affected.

Test your function on your hurricane dictionary.

In [7]:
# write your count affected areas function here:

def count_affected_areas(hurricane_by_name_dictionary):
    number_of_hurricane_by_area_dictionary = {}
    for (key,value) in hurricane_by_name_dictionary.items():
        for area in value["Areas Affected"]:
            if not area in number_of_hurricane_by_area_dictionary:
                number_of_hurricane_by_area_dictionary[area] = 1
            else:
                number_of_hurricane_by_area_dictionary[area] += 1
    return number_of_hurricane_by_area_dictionary
            
affected_areas_dictionary = count_affected_areas(hurricane_name_dictionary)

for (key,value) in affected_areas_dictionary.items():
    print("{key}: {value}".format(key=key,value=value))

Central America: 9
Mexico: 7
Cuba: 6
Florida: 6
The Bahamas: 7
Lesser Antilles: 4
United States East Coast: 3
Atlantic Canada: 3
Northeastern United States: 2
Jamaica: 4
Cayman Islands: 1
Bermuda: 2
Texas: 4
Tamaulipas: 1
Yucatn Peninsula: 3
Georgia: 1
The Carolinas: 1
Virginia: 1
Southeastern United States: 1
Southwestern Quebec: 1
New England: 1
Louisiana: 1
Midwestern United States: 1
The Caribbean: 8
United States Gulf Coast: 6
United States East coast: 1
South Texas: 1
Venezuela: 3
Hispaniola: 1
South Florida: 1
Greater Antilles: 2
Bahamas: 2
Eastern United States: 1
Ontario: 1
Windward Islands: 1
Nicaragua: 1
Honduras: 1
Antilles: 1
Colombia: 1
Cape Verde: 1
British Virgin Islands: 1
U.S. Virgin Islands: 1
Virgin Islands: 1
Puerto Rico: 1
Dominican Republic: 1
Turks and Caicos Islands: 1
United States Gulf Coast (especially Florida Panhandle): 1


# Task 5

Write a function that finds the area affected by the most hurricanes, and how often it was hit.

Test your function on your affected area dictionary.

In [8]:
def most_affected_area(affected_area_dictionary):
    most_affected_area = ''
    number_of_hurricanes = -1
    for (key,val) in affected_area_dictionary.items():
        if val > number_of_hurricanes:
            most_affected_area = key
            number_of_hurricanes = val
        elif val == number_of_hurricanes:
            if not isinstance(most_affected_area, list):
                most_affected_area = [most_affected_area, key]
            else:
                most_affected_area.append(key)
    return (most_affected_area,number_of_hurricanes)

most_affected_area_and_how_often = most_affected_area(affected_areas_dictionary)
print('{area} was affected by the most hurricanes ({num} times).'.format(area=most_affected_area_and_how_often[0],
                                                                         num=most_affected_area_and_how_often[1]))

Central America was affected by the most hurricanes (9 times).


# Task 6 

Write a function that finds the hurricane that caused the greatest number of deaths, and how many deaths it caused.

Test your function on your hurricane dictionary.

In [9]:
def greatest_number_of_deaths(hurricane_by_name_dictionary):
    hurricane_name = ''
    number_of_deaths = -1
    for (key,val) in hurricane_by_name_dictionary.items():
        deaths = val['Deaths']
        if deaths > number_of_deaths:
            hurricane_name = val['Name']
            number_of_deaths = deaths
    return (hurricane_name,number_of_deaths)

area_with_greatest_number_of_deaths = greatest_number_of_deaths(hurricane_name_dictionary)
print('Hurricane {name} caused the greatest number of deaths ({num} deaths).'.format(
    name=area_with_greatest_number_of_deaths[0], num=area_with_greatest_number_of_deaths[1]))

Hurricane Mitch caused the greatest number of deaths (19325 deaths).


# Task 7

Just as hurricanes are rated by their windspeed, you want to try rating hurricanes based on other metrics.

Write a function that rates hurricanes on a mortality scale according to the following ratings, where the key is the rating and the value is the upper bound of deaths for that rating.

`mortality_scale = {0: 0,
                   1: 100,
                   2: 500,
                   3: 1000,
                   4: 10000}`
                   
For example, a hurricane with a 1 mortality rating would have resulted in greater than 0 but less than or equal to 100 deaths. A hurricane with a 5 mortality rating would have resulted in greater than 10000 deaths.

Store the hurricanes in a new dictionary where the keys are mortality ratings and the values are lists containing a dictionary for each hurricane that falls into that mortality rating.

Test your function on your hurricane dictionary.

In [10]:
def catgeorize_by_mortality(hurricane_by_name_dictionary):
    catgeorized_by_mortality_dictionary = {0:[], 1:[], 2:[], 3:[], 4:[], 5:[]}
    for value in hurricane_by_name_dictionary.values():
        deaths = value["Deaths"]
        if deaths <= 0:
            catgeorized_by_mortality_dictionary[0].append(value)
        elif deaths <= 100:
            catgeorized_by_mortality_dictionary[1].append(value)
        elif deaths <= 500:
            catgeorized_by_mortality_dictionary[2].append(value)
        elif deaths <= 1000:
            catgeorized_by_mortality_dictionary[3].append(value)
        elif deaths <= 10000:
            catgeorized_by_mortality_dictionary[4].append(value)
        else:
            catgeorized_by_mortality_dictionary[5].append(value)
    return catgeorized_by_mortality_dictionary
            
catgeorized_by_mortality_dictionary = catgeorize_by_mortality(hurricane_name_dictionary)
for (key,value) in catgeorized_by_mortality_dictionary.items():
    print("{key}: {value}".format(key=key,value=value))
    print()

0: []

1: [{'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 0, 'Deaths': 90}, {'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 0, 'Deaths': 16}, {'Name': 'Carol', 'Month': 'September', 'Year': 1953, 'Max Sustained Wind': 160, 'Areas Affected': ['Bermuda', 'New England', 'Atlantic Canada'], 'Damage': 2000000.0, 'Deaths': 5}, {'Name': 'Carla', 'Month': 'September', 'Year': 1961, 'Max Sustained Wind': 175, 'Areas Affected': ['Texas', 'Louisiana', 'Midwestern United States'], 'Damage': 326000000.0, 'Deaths': 43}, {'Name': 'Edith', 'Month': 'September', 'Year': 1971, 'Max Sustained Wind': 160, 'Areas Affected': ['The Caribbean', 'Central America', 'Mexico', 'United States Gulf Coast'], 'Damage': 25400000.0, 'Deaths': 37}, {'Name': 'Anita', 'Month': 'September', 

# Task 8

Write a function that finds the hurricane that caused the greatest damage, and how costly it was.

Test your function on your hurricane dictionary.

In [11]:
# write your greatest damage function here:
def greatest_damage(hurricane_by_name_dictionary):
    hurricane_name = ''
    greatest_damage = -1
    for value in hurricane_by_name_dictionary.values():
        damage = value['Damage']
        if isinstance(damage, float) and damage > greatest_damage:
            hurricane_name = value['Name']
            greatest_damage = damage
    return (hurricane_name,greatest_damage)

hurricane_with_greatest_damage = greatest_damage(hurricane_name_dictionary)
print('Hurricane {name} caused the greatest damage: ${num}.'.format(
    name=hurricane_with_greatest_damage[0], num=hurricane_with_greatest_damage[1]))

Hurricane Katrina caused the greatest damage: $125000000000.0.


# Task 9


Lastly, you want to rate hurricanes according to how much damage they cause.

Write a function that rates hurricanes on a damage scale according to the following ratings, where the key is the rating and the value is the upper bound of damage for that rating.

`damage_scale = {0: 0,
                1: 100000000,
                2: 1000000000,
                3: 10000000000,
                4: 50000000000}`
                
For example, a hurricane with a 1 damage rating would have resulted in damages greater than 0 USD but less than or equal to 100000000 USD. A hurricane with a 5 damage rating would have resulted in damages greater than 50000000000 USD (talk about a lot of money).

Store the hurricanes in a new dictionary where the keys are damage ratings and the values are lists containing a dictionary for each hurricane that falls into that damage rating.

Test your function on your hurricane dictionary.

In [12]:
def catgeorize_by_damage(hurricane_by_name_dictionary):
    catgeorized_by_damage_dictionary = {0:[], 1:[], 2:[], 3:[], 4:[], 5:[]}
    for value in hurricane_by_name_dictionary.values():
        damage = value["Damage"]
        if damage <= 0:
            catgeorized_by_damage_dictionary[0].append(value)
        elif damage <= 100000000:
            catgeorized_by_damage_dictionary[1].append(value)
        elif damage <= 1000000000:
            catgeorized_by_damage_dictionary[2].append(value)
        elif damage <= 10000000000:
            catgeorized_by_damage_dictionary[3].append(value)
        elif damage <= 50000000000:
            catgeorized_by_damage_dictionary[4].append(value)
        else:
            catgeorized_by_damage_dictionary[5].append(value)
    return catgeorized_by_damage_dictionary
            
catgeorized_by_damage_dictionary = catgeorize_by_damage(hurricane_name_dictionary)
for (key,value) in catgeorized_by_damage_dictionary.items():
    print("{key}: {value}".format(key=key,value=value))
    print()

0: [{'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 0, 'Deaths': 90}, {'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 0, 'Deaths': 16}, {'Name': 'Labor Day', 'Month': 'September', 'Year': 1935, 'Max Sustained Wind': 185, 'Areas Affected': ['The Bahamas', 'Florida', 'Georgia', 'The Carolinas', 'Virginia'], 'Damage': 0, 'Deaths': 408}, {'Name': 'Anita', 'Month': 'September', 'Year': 1977, 'Max Sustained Wind': 175, 'Areas Affected': ['Mexico'], 'Damage': 0, 'Deaths': 11}]

1: [{'Name': 'San Felipe II Okeechobee', 'Month': 'September', 'Year': 1928, 'Max Sustained Wind': 160, 'Areas Affected': ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], 'Damage': 100000000.0, 'Deaths': 4000}, {'Name': 'Cuba II', 'Month': 'November', 'Ye